community/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('authentication.urls')),
    path('', include('user_profile.urls')),
    path('', include('questions.urls'))
]

home/urls.py
from django.urls import path

from .views import home

urlpatterns = [
    path('', home, name='home'),
]

questions/urls.py
from django.urls import include, path

from .views import (
    CreateQuestionView, QuestionDetailView,
    QuestionListView,
)
from .views import create_answer

app_name = 'questions'    # 指定了路由名称

urlpatterns = [
    path('questions/', include(([
        path('', QuestionListView.as_view(), name='question_list'),
        path('add/', CreateQuestionView.as_view(), name='question_add'),
        path('<int:pk>/', QuestionDetailView.as_view(), name='question_detail'),
        path('<int:pk>/add', create_answer, name='answer_add'),
    ])))
]

user_profile/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import ProfileDetailView, UpdateProfileView

app_name = 'user_profile'

urlpatterns = [
    path('user/', include(([
        path('<int:user_id>/', ProfileDetailView.as_view(), name='profile'),
        path('<int:user_id>/edit', UpdateProfileView.as_view(), name='update_profile'),
    ])))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questions/models.py
from django.db import models
import markdown
# Create your models here.
from authentication.models import User


class Question(models.Model):
    """
    Question 模型
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=2000)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Question'
        verbose_name_plural = 'Questions'
        ordering = ('-update_date',)  # 比须是元组

    def __str__(self):
        return self.title

    def get_answers(self):
        return Answer.objects.filter(question=self)

    def get_answers_count(self):
        return Answer.objects.filter(questions=self).count()

    def get_description_as_markdown(self):  # 此方法将问题文本渲染为 Markdown 格式
        return markdown.markdown(self.description, safe_mode='escape')


class Answer(models.Model):
    """
    Answer for a question.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    description = models.TextField(max_length=2000)
    create_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Answer'
        verbose_name_plural = 'Answers'
        ordering = ('create_date',)

    def __str__(self):
        return self.description

    def get_description_as_markdown(self):  # 此方法将回答文本渲染为 Markdown 格
        return markdown.markdown(self.description, safe_mode='escape')

questions/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from .models import Question, Answer


class QuestionForm(forms.ModelForm):
    """
    问题表单
    """
    title = forms.CharField(
        max_length=255,
        label=_('Title'),
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    description = forms.CharField(
        max_length=2000,
        label=_('Description'),
        widget=forms.Textarea(attrs={'class': 'form-control'}),
        help_text=_('Write the question\'s description...')
    )

    class Meta:
        model = Question
        fields = ['title', 'description']


class AnswerForm(forms.ModelForm):
    """答案表单"""
    description = forms.CharField(
        max_length=2000,
        widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '4'})
    )

    class Meta:
        model = Answer
        fields = ['description']

questions/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.views.generic import (CreateView, ListView)

from .models import Question, Answer
from .forms import AnswerForm, QuestionForm


# Create your views here.
@method_decorator([login_required], name='dispatch')
class CreateQuestionView(CreateView):
    """
    @method_decorator([login_required], name='dispatch')装饰器声明了只有登录用户才能访问此页面，
    这样避免了非登录用户创建问题的情况。
    继承自CreateView,可以很方便的给模板传入表单信息.
    model指定了创建的模型,
    form_class指定了使用的表单,也就是先前创建的QuestionForm,
    template_name指定使用的模板.

    form_valid是当表单传入合法数据后执行的方法.在传入合法数据后,
    使用form.save(commit=False)暂时先不将数据保存至数据库,
    先指定问题的提问人,创建时间和更改时间,最后再保存至数据库.
    在所有操作完成后,再重定向至问题详情页.
    """
    model = Question
    form_class = QuestionForm
    template_name = 'questions/ask_question.html'

    def form_valid(self, form):
        question = form.save(commit=False)  # 当commit 为false 则会生成一个对象
        question.user = self.request.user
        question.update_date = question.create_date
        question.save()
        form.save_m2m()
        messages.success(self.request, 'The question was created with success!')
        return redirect('questions:question_detail', question.pk)


class QuestionListView(ListView):
    """
    show the list of questions.
    继承自ListView可以很方便的向模板传入集合数据.
    model指定了使用的模型为Question,
    ordering指定按照更改的时间顺序排序,
    context_object_name指定了传入模板的上下文中集合的名称,
    queryset指定了返回的集合,这里返回了包含所有问题的集合,
    paginate_by指定每页显示的最多问题数
    """
    model = Question
    ordering = ('update_date')
    context_object_name = 'questions'
    template_name = 'questions/questions_list.html'
    queryset = Question.objects.all()
    paginate_by = 1


class QuestionDetailView(CreateView):
    """
    show question detail
    继承自CreateView,可以很方便的给模板传入表单信息.
    model指定了创建的模型,form_class指定了使用的表单,也就是先前创建的AnswerForm,
    template_name指定使用的模板.

    get_context_data方法是向模板传入上下文的关键方法.
    其中的super方法继承了父类的上下文,在这里我们增加传入了问题及其回答的字段
    """
    model = Answer
    form_class = AnswerForm
    template_name = 'questions/question_detail.html'

    def get_context_data(self, **kwargs):
        question_id = self.kwargs.get('pk')
        question = Question.objects.get(pk=question_id)
        kwargs['question'] = question
        if Answer.objects.filter(question=question):
            kwargs['answers'] = Answer.objects.filter(question=question)

        context = super().get_context_data(**kwargs)
        return context

@login_required
def create_answer(request, pk):
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = Answer()
            answer.user = request.user
            answer.question = Question.objects.get(pk=pk)
            answer.description = form.cleaned_data.get('description')
            answer.save()
            messages.success(request, 'The answer was created successfully.')
            return redirect('questions:question_detail', answer.question.pk)
    return redirect('questions:question_detail', pk)

templates/questions/answers_list.html
{% load i18n %}
{% load humanize %}
{% load staticfiles %}

<div class="row answer" answer-id="{{ answer.id }}">
    <div class="col-md-11">
        <div class="answer-user">
{#            <a><img src="{{ answer.user.get_picture }}" class="user-picture"></a>#}
            <a><img src="{% static 'img/user.png' %}" class="user"></a>
            <a href="{% url 'user_profile:profile' answer.user.id %}">{{ answer.user.username }}</a>
            <small class="answered">{% trans "answered" %} {{ answer.create_date|naturaltime }}</small>
        </div>
        <div class="answer-description">
            {{ answer.get_description_as_markdown|safe }}
        </div>
    </div>
</div>

templates/questions/ask_question.html
{% extends 'base.html' %}

{% load i18n %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block head %}
  <link href="{% static 'css/signup.css' %}" rel="stylesheet">
{% endblock head %}

{% block main %}

  <div class="cover">
    <h1 class="logo"><a href="{% url 'home' %}">Community</a></h1>
    <div class="signup">
        <h2>{% trans 'Ask a question' %}</h2>
        <form  method="post" novalidate>
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="form-group{% if field.errors %} has-error{% endif %}">
                    <label for="{{ field.label }}">{{ field.label }}</label>
                    {{ field }}
                    {% if field.help_text %}
                        <span class="help-block">{{ field.help_text|safe }}</span>
                    {% endif %}
                    {% for error in field.errors %}
                        <label class="control-label">{{ error }}</label>
                    {% endfor %}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary btn-lg">{% trans 'Create an account' %}</button>
        </form>
    </div>
  </div>

{% endblock main %}

templates/questions/create_answer.html
{% load i18n %}
{% load staticfiles %}
{% load humanize %}

<form action="{% url 'questions:answer_add' question.id %}" method="POST" role="form">
    {% csrf_token %}
    <div class="form-group">
        {{ form.description }}
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">{% trans "Post Your Answer" %}</button>
    </div>
</form>

templates/questions/question_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}
{% load humanize %}

{% block head %}
    <link href="{% static 'css/questions.css' %}" rel="stylesheet">
    <script src="{% static 'js/questions.js' %}"></script>
{% endblock head %}

{% block main %}
    <ol class="breadcrumb">
        <li><a href="{% url 'questions:question_list' %}">{% trans "Questions" %}</a></li>
        <li class="active">{% trans "Question" %}</li>
    </ol>
    <div class="row question" question-id="{{ question.id }}">
        {% csrf_token %}
        <div class="col-md-11">
            <h2>{{ question.title }}</h2>

            <div class="question-user">
                <a href="{% url 'user_profile:profile' question.user.id %}"><img src="{% static 'img/user.png' %}"
                                                                          class="user"></a>
                <small class="asked">{% trans 'asked' %} {{ question.update_date|naturaltime }}</small>
            </div>
            <div class="question-description">
                {{ question.get_description_as_markdown|safe }}
            </div>
            {% if question.get_tag_list %}
                <p>
                    {% for tag in question.get_tag_list %}
                        <span class="label label-primary">{{ tag }}</span>
                    {% endfor %}
                </p>
            {% endif %}
        </div>
    </div>
    <h4 class="page-header">{% trans 'Answers' %}</h4>
    <div class="answers">
        {% for answer in question.get_answers %}
            {% include 'questions/answers_list.html' with answer=answer %}
        {% endfor %}
        {% if not user.is_anonymous %}
            <h4>{% trans 'Write your Answer' %}</h4>
            {% include 'questions/create_answer.html' with question=question user=user %}
        {% endif %}
    </div>
{% endblock main %}

templates/questions/questions_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block title %}{% trans 'Questions' %}{% endblock %}

{% block head %}
    <link href="{% static 'css/questions.css' %}" rel="stylesheet">
    <script src="{% static 'js/questions.js' %}"></script>
{% endblock head %}

{% block main %}
    <div class="page-header">
        {% if not user.is_anonymous %}
            <a href="{% url 'questions:question_add' %}" class="btn btn-primary pull-right">
                <span class="glyphicon glyphicon-bullhorn"></span> {% trans "Ask Question" %}
            </a>
        {% endif %}
        <h1>{% trans "Questions" %}</h1>
    </div>
    <div class="questions">
        {% for question in questions %}
            <a href="{% url 'questions:question_detail' question.id %}"> {{ question.title }} </a>
            {% if question.update_date != question.create_date %}
                <p>{% trans 'update at' %} {{ question.update_date }}</p>
            {% else %}
                <p>{% trans 'create at' %} {{ question.create_date }}</p>
            {% endif %}
        {% empty %}
            <a>No questions now.</a>
        {% endfor %}

        {% if is_paginated %}
            <div class="pagination">
                <span class="page-link">
                    {% if page_obj.has_previous %}
                        <a href="/questions?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </span>
                {% if page_obj.has_next %}
                    <a href="/questions?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
                </span>
            </div>
        {% endif %}


    </div>
{% endblock main %}