community/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('authentication.urls')),
    path('', include('user_profile.urls')),
    path('', include('questions.urls'))
]

home/urls.py
from django.urls import path

from .views import home

urlpatterns = [
    path('', home, name='home'),
]

user_profile/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import ProfileDetailView, UpdateProfileView

app_name = 'user_profile'

urlpatterns = [
    path('user/', include(([
        path('<int:user_id>/', ProfileDetailView.as_view(), name='profile'),
        path('<int:user_id>/edit', UpdateProfileView.as_view(), name='update_profile'),
    ])))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_profile/models.py
from django.db import models
# 信号，新知识
from django.db.models.signals import post_save
from authentication.models import User


# Create your models here.
class Profile(models.Model):
    """
    profile of a user .
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    url = models.CharField(max_length=50, null=True, blank=True)
    location = models.CharField(max_length=50, null=True, blank=True)
    job_title = models.CharField(max_length=50, null=True, blank=True)
    avatar = models.ImageField(upload_to='pic_folder', default='img/user.png')

    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    post_save.connect(create_user_profile, sender=User)
    post_save.connect(save_user_profile, sender=User)

user_profile/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
# 新知识
from django.utils.decorators import method_decorator
from django.views.generic import (TemplateView, UpdateView)
# Create your views here.

from authentication.models import User
from .models import Profile


@method_decorator([login_required], name='dispatch')
class ProfileDetailView(TemplateView):
    """
    show the profile
    """
    # 如何使用django中的通用视图
    # 指定使用的数据模型
    model = Profile
    # 指定使用的模板文件，用于渲染数据
    template_name = 'user_profile/profile.html'

    # 重写这个方法，用于向模板传递数据
    def get_context_data(self, **kwargs):
        # 获取用户id
        context = super(ProfileDetailView, self).get_context_data(**kwargs)  # why?
        user_id = self.kwargs.get('user_id')  # why?
        context['user'] = User.objects.get(id=user_id)
        context['profile'] = Profile.objects.get(user_id=user_id)
        return context


class UpdateProfileView(UpdateView):
    """
    update the profile
    """
    model = Profile
    fields = ['avatar', 'url', 'location']
    template_name = 'user_profile/profile_update.html'

    def get_object(self, queryset=None):
        # 重写方法,获得当前视图使用的对象
        return Profile.objects.get(user_id=self.kwargs.get('user_id'))

    def form_valid(self, form):
        """
        do something before save the profile
        :param form:
        :return:
        """
        profile = form.save(commit=False)
        profile.save()
        form.save_m2m()
        return redirect('user_profile:profile', self.kwargs.get('user_id'))

    def get_success_url(self):
        return reverse('user_profile:profile', self.kwargs.get('user_id'))

templates/user_profile/profile.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block title %} Community > {{ user.username }} {% endblock %}

{% block head %}
  <link href="{% static 'css/profile.css' %}" rel="stylesheet">
  <script src="{% static 'js/jquery.bullseye-1.0-min.js' %}"></script>
{% endblock head %}

{% block main %}
 <div class="page-header">
    <a href="{% url 'user_profile:update_profile' user_id %}">{% trans 'Edit' %}</a>
  </div>
  <div class="profile">
    <div class="row">

      <div class="col-md-9">
        <h4>{{ user.username }}</h4>
          <p>{% trans 'Your are the' %} {{ user.id }} {% trans 'user.' %}</p>
          <p>{% trans 'Last login at' %} {{ user.last_login }} .</p>
        <div class="stream-update">
        </div>
        <div class="load">
          <img style="height:12%" src="{{MEDIA_URL}}{{profile.avatar.url}}" alt="" class="img-circle img-responsive">

        </div>
          <div class="float-right">
            <ul>
                <li>url: {{ profile.url }}</li>
                <li>location: {{ profile.location }}</li>
                <li>job: {{ profile.job_title }}</li>
            </ul>
        </div>
    </div>
  </div>

{% endblock main %}

templates/user_profile/profile_update.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %} Community > {{ user.username }} {% endblock %}

{% block head %}
  <link href="{% static 'css/profile.css' %}" rel="stylesheet">
{#  <link href="{% static 'css/feeds.css' %}" rel="stylesheet">#}
  <script src="{% static 'js/jquery.bullseye-1.0-min.js' %}"></script>
{#  <script src="{% static 'js/feeds.js' %}"></script>#}
{% endblock head %}

{% block main %}
  <div class="page-header">
    <h1>{{ page_user.profile.get_screen_name }} {% if page_user.get_full_name %}<small>({{ page_user.username }})</small>{% endif %}</h1>
  </div>
  <div class="profile">
    <div class="row">
      <div class="col-md-9">
        <h4>{{ user.username }}</h4>
          <p>{% trans 'Your are the' %} {{ user.id }} {% trans 'user.' %}</p>
          <p>{% trans 'Last login at' %} {{ user.last_login }} .</p>
        <div class="stream-update">
{#          <a href="#"><span class="new-posts"></span> new posts</a>#}
        </div>
        <div class="load">
          <img style="height:12%" src="{{MEDIA_URL}}{{profile.avatar.url}}" alt="" class="img-circle img-responsive">
        </div>
        <form method="post" novalidate>
            {% csrf_token %}
            {{ form | crispy }}
            <button type="submit" class="btn btn-primary btn-lg">{% trans 'Update profile' %}</button>
        </form>
      </div>
    </div>
  </div>
{% endblock main %}