authentication/urls.py
from django.urls import include, path
#  django 内置的认证视图
from django.contrib.auth import views as auth_views

from .views import UserSignView


app_name = 'authentication'


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='authentication/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', UserSignView.as_view(), name='signup'),
]

community/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('authentication.urls')),
    path('', include('user_profile.urls')),
    path('', include('questions.urls'))
]

home/urls.py
from django.urls import path

from .views import home

urlpatterns = [
    path('', home, name='home'),
]

questions/urls.py
from django.urls import include, path

from .views import (
    CreateQuestionView, QuestionDetailView,
    QuestionListView,
)
from .views import create_answer

app_name = 'questions'    # 指定了路由名称

urlpatterns = [
    path('questions/', include(([
        path('', QuestionListView.as_view(), name='question_list'),
        path('add/', CreateQuestionView.as_view(), name='question_add'),
        path('<int:pk>/', QuestionDetailView.as_view(), name='question_detail'),
        path('<int:pk>/add', create_answer, name='answer_add'),
    ])))
]

user_profile/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import ProfileDetailView, UpdateProfileView

app_name = 'user_profile'

urlpatterns = [
    path('user/', include(([
        path('<int:user_id>/', ProfileDetailView.as_view(), name='profile'),
        path('<int:user_id>/edit', UpdateProfileView.as_view(), name='update_profile'),
    ])))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{% get_current_language as LANGUAGE_CODE %}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Community{% endblock %}</title>
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/bootcamp.css' %}" rel="stylesheet">
    <script src="https://cdn.bootcss.com/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% block head %}
    {% endblock head %}
</head>
<body>
{% block body %}
    <header>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <a class="navbar-brand" href="{% url 'questions:question_list' %}">Community</a>
                </div>
                <div class="collapse navbar-collapse" id="menu">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'questions:question_list' %}">{% trans 'Q&A' %}</a></li>
                    </ul>

                    {% if not hide_search %}
                        <form class="navbar-form navbar-left" role="search" action="#">
                            <div class="input-group" style="width:210px">
                                <input type="text" class="form-control" name="q" placeholder="{% trans 'Search' %}">
                    <span class="input-group-btn">
                      <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span>
                      </button>
                    </span>
                            </div>
                        </form>
                    {% endif %}

                    <ul class="nav navbar-nav navbar-right">
                        {% if not user.is_anonymous %}
                            <li><a href="{% url 'user_profile:profile' user.id %}">{{ user.get_username }}</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'user_profile:profile' user.id %}">{% trans 'profile' %}</a></li>
                                    <li class="divider"></li>
                                    <li><a href="{% url 'authentication:logout' %}">{% trans 'Log out' %}</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li><a href="{%  url 'authentication:signup' %}">{% trans 'Sign up' %}</a></li>
                            <li><a href="{% url 'authentication:login' %}">{% trans 'Log in' %}</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main>
        <div class="container">
            {% block main %}
            {% endblock main %}
        </div>
    </main>
{% endblock body %}
<script src="{% static 'js/ga.js' %}"></script>
</body>
</html>